#!/bin/bash
openvcan="$(ifconfig | grep -Po 'vcan[0-9]*')"
if [ -z "$openvcan" ]
then
	openvcan="Nessuna vcan attiva"
fi
echo Vcan attive: ${openvcan}
echo "Inserire numero vcan"
read nvcan
CAN_PORT="vcan${nvcan}" 
sudo modprobe vcan
sudo ip link add dev $CAN_PORT type vcan
sudo ip link set up $CAN_PORT
echo "Virtual can aperta nella porta $CAN_PORT"
